# 🔹 Basic Level

In [16]:
#1

# Create a NumPy array using a Python list.

# Input: [1,2,3,4]
# Output: [1 2 3 4]

import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [17]:
#2

# Create a NumPy array of zeros.

# Input: 5
# Output: [0. 0. 0. 0. 0.]

import numpy as np

zero = np.zeros(5)
print(zero)



[0. 0. 0. 0. 0.]


In [18]:
#3

# Create a NumPy array of ones.

# Input: 4
# Output: [1. 1. 1. 1.]
import numpy as np
one = np.ones(4)
print(one)


[1. 1. 1. 1.]


In [19]:
#4

# Create an array using arange().

# Input: 1 to 6
# Output: [1 2 3 4 5]



In [20]:
#5

# Create a NumPy array with evenly spaced values using linspace().

# Input: 0 to 10, 5 values
# Output: [0. 2.5 5. 7.5 10.]

import numpy as np

lin = np.linspace(0,10,5)
print(lin)


[ 0.   2.5  5.   7.5 10. ]


In [21]:
#6

# Find dimensions of a NumPy array.

# Input: [[1,2],[3,4]]
# Output: 2
import numpy as np
arr = np.array([[1,2],[3,4]])
np.ndim(arr)



2

In [22]:
#7

# Find shape of a NumPy array.

# Input: [[1,2,3],[4,5,6]]
# Output: (2,3)

import numpy as np

a = np.array([[1,2,3],[4,5,6]])
np.shape(a)

(2, 3)

In [23]:
# 8

# Find datatype of array elements.

# Input: [1,2,3]
# Output: int
import numpy as np

b = np.array([1,2,3])
print(b.dtype)


int64


In [24]:
#9

# Create an identity matrix using NumPy.

# Input: 3
# Output:

# [[1 0 0]
#  [0 1 0]
#  [0 0 1]]
import numpy as np

a = np.identity(3)
print(a)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
#10

# Create a diagonal matrix using NumPy.

# Input: [1,2,3]
# Output:

# [[1 0 0]
#  [0 2 0]
#  [0 0 3]]

import numpy as np
a = np.array([1,2,3])
b = np.diag(a)
print(b)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


# 🔹 Intermediate Level

In [26]:
#11

# Add two NumPy arrays.

# Input: [1,2,3], [4,5,6]
# Output: [5 7 9]
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
c = a+b
print(c)


[5 7 9]


In [27]:
#12

# Subtract two arrays.

# Input: [10,20,30], [1,2,3]
# Output: [9 18 27]
import numpy as np
a = np.array([10,20,30])
b = np.array([1,2,3])
c = a-b
print(c)


[ 9 18 27]


In [28]:
#13

# Multiply array elements.

# Input: [1,2,3], [2,2,2]
# Output: [2 4 6]
import numpy as np

a = np.array([1,2,3])
b = np.array([2,2,2])
c = a*b
print(c)


[2 4 6]


In [29]:
#14

# Divide array elements.

# Input: [10,20,30], [2,5,3]
# Output: [5. 4. 10.]
import numpy as np

a = np.array([10,20,30])
b = np.array([2,5,3])
c = a/b
print(c)


[ 5.  4. 10.]


In [30]:
#15

# Find maximum element of array.

# Input: [2,8,1,9]
# Output: 9

import numpy as np

arr = np.array([2,8,1,9])
max = np.max(arr)
print(max)

9


In [31]:
#16

# Find minimum element of array.

# Input: [2,8,1,9]
# Output: 1
import numpy as np

arr = np.array([2,8,1,9])
min = np.min(arr)
print(min)


1


In [32]:
#17

# Find sum of all array elements.

# Input: [1,2,3,4]
# Output: 10

import numpy as np

arr = np.array([1,2,3,4])
sum = np.sum(arr)
print(sum)


10


In [33]:
#18

# Find mean of array.

# Input: [2,4,6,8]
# Output: 5.0

import numpy as np

arr = np.array([2,4,6,8])
mean = np.mean(arr)
print(mean)


5.0


In [34]:
#19

# Find square root of array elements.

# Input: [1,4,9,16]
# Output: [1. 2. 3. 4.]
import numpy as np

arr = np.array([1,4,9,16])
sqr = np.sqrt(arr)
print(sqr)

[1. 2. 3. 4.]


In [35]:
#20

# Find square of all elements in array.

# Input: [1,2,3,4]
# Output: [1 4 9 16]
import numpy as np

arr = np.array([1,2,3,4])
sq = np.square(arr)
print(sq)

[ 1  4  9 16]


# 🔹 Array Indexing & Slicing


In [36]:
#21

# Access first element of array.

# Input: [10,20,30]
# Output: 10

import numpy as np

arr = np.array([10,20,30])
print(arr[0])


10


In [37]:
#22

# Access last element of array.

# Input: [10,20,30]
# Output: 30

import numpy as np

arr = np.array([10,20,30])
print(arr[-1])
print(arr[2])

30
30


In [38]:
#23

# Slice array elements from index 1 to 4.

# Input: [1,2,3,4,5]
# Output: [2 3 4]

import numpy as np

arr = np.array([1,2,3,4,5])
print(arr[1:4])

[2 3 4]


In [39]:
#24

# Reverse a NumPy array.

# Input: [1,2,3,4]
# Output: [4 3 2 1]

import numpy as np

arr = np.array([1,2,3,4])
print(a[::-1])

[30 20 10]


In [40]:
#25

# Access specific row from 2D array.

# Input:

# [[1,2],
#  [3,4]]

# Output:
# [3 4]
import numpy as np

arr = np.array([[1,2],[3,4]])

print(arr[1])

[3 4]


In [41]:
#26

# Access specific column from 2D array.

# Input:

# [[1,2],
#  [3,4]]

# Output:
# [2 4]

import numpy as np

arr = np.array([[1,2],[3,4]])

print(arr[0:2,1])

[2 4]


In [42]:
#27

# Replace element in array.

# Input: [1,2,3], replace index 1 with 10
# Output: [1 10 3]

import numpy as np

arr = np.array([1,2,3])
print("Orignal array:",arr)
arr[1] = 10
print("After replacing:",arr)

Orignal array: [1 2 3]
After replacing: [ 1 10  3]


# 🔹 Logical / Matrix Questions


In [43]:
#28

# Create a 3x3 matrix using NumPy.

import numpy as np

arr3x3 = np.array([[1,2,3],[1,2,3],[1,2,3]])
print(arr3x3)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [44]:
#29

# Transpose a matrix.

# Input:

# [[1,2],
#  [3,4]]

# Output:

# [[1 3]
#  [2 4]]

import numpy as np

a = np.array([[1,2],
             [3,4]])
b = np.transpose(a)
print(b)

[[1 3]
 [2 4]]


In [45]:
#30

# Find determinant of matrix.

# Input:

# [[1,2],
#  [3,4]]

# Output:
# -2
import numpy as np
a = np.array([[1,2],
              [3,4]])

b = np.linalg.det(a)
print(b)

-2.0000000000000004


In [46]:
#31
#  perform matrix multiplication.

# Input:
# Matrix A = [[1,2]]
# Matrix B = [[3],[4]]

# Output:
# [[11]]

import numpy as np
arr1 = np.array([[1,2]])
arr2 = np.array([[3],[4]])

arr3 = np.matmul(arr1,arr2)
print(arr3)


[[11]]


In [47]:
#32

# Find eigenvalues of matrix.

# Input:

# [[2,0],
#  [0,3]]

# Output:
# [2,3]
import numpy as np

arr = np.array([[2,0],[0,3]])
eg = np.linalg.eigvals(arr)
print(eg)



[2. 3.]


In [48]:
#33
# Reshape array into 2x2 matrix.

# Input: [1,2,3,4]
# Output:

# [[1 2]
#  [3 4]]

import numpy as np
a = np.array([1,2,3,4])
c = a.reshape(2,2)
print(c)

[[1 2]
 [3 4]]


In [49]:
#34
# Flatten a multidimensional array.

# Input:

# [[1,2],
#  [3,4]]

# Output:
# [1 2 3 4]

import numpy as np
a = np.array( [[1,2],
                [3,4]])
b = a.reshape(-1)
print(b)

[1 2 3 4]


In [50]:
# #35

# Concatenate two NumPy arrays.

# Input: [1,2], [3,4]
# Output: [1 2 3 4]

import numpy as np

arr1 = np.array([1, 2])

arr2 = np.array([3, 4])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4]


# 🔹 Advanced Level


In [51]:
#36

# Generate random integers using NumPy.

# Input: range 1 to 10
# Output: Random values
import numpy as np

num = np.random.randint(1,10)

print(num)


4


In [52]:
#37

# Sort a NumPy array.

# Input: [5,2,8,1]
# Output: [1 2 5 8]

import numpy as np

arr = np.array([5,2,8,1])
new = np.sort(arr)
print(new)


[1 2 5 8]


In [53]:
#38

# Find unique elements in array.

# Input: [1,2,2,3,1]
# Output: [1 2 3]

import numpy as np

arr = np.array([1,2,2,3,1])
new = np.unique(arr)
print(new)

[1 2 3]


In [54]:
#39

# Count frequency of elements.

# Input: [1,2,2,3,3,3]
# Output:
# 1→1, 2→2, 3→3

import numpy as np

a = np.array([1,2,2,3,3,3])
unique,count = np.unique(a,return_counts=True)

for i in range(len(unique)):
    print(f"{unique[i]}→ {count[i]}")

1→ 1
2→ 2
3→ 3


In [55]:
#40

# Find indices of elements greater than 5.

# Input: [1,6,3,8,2]
# Output: [1 3]

import numpy as np
arr = np.array([1,6,3,8,2])
b = np.where(arr>5)
print(b)

(array([1, 3]),)


In [56]:
#41

# Create diagonal matrix using NumPy.

# Input: [1,2,3]
# Output:

# [[1 0 0]
#  [0 2 0]
#  [0 0 3]]
import numpy as np

a = np.array([1,2,3])
b = np.diag(a)
print(b)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [57]:
#42

# Stack two arrays vertically.

# Input:
# [1,2], [3,4]

# Output:

# [[1 2]
#  [3 4]]
import numpy as np
arr1 = np.array([1,2])
arr2 = np.array([3,4])
arr3 = np.vstack((arr1,arr2))
print(arr3)

[[1 2]
 [3 4]]


In [58]:
#43
# Stack two arrays horizontally.

# Input:
# [1,2], [3,4]

# Output:
# [1 2 3 4]
import numpy as np
arr1 = np.array([1,2])
arr2 = np.array([3,4])
arr3 = np.hstack((arr1,arr2))
print(arr3)

[1 2 3 4]


In [59]:
#44

# Create boolean mask for even numbers.

# Input: [1,2,3,4,5]
# Output:
# [False True False True False]

import numpy as np
arr = np.array([1,2,3,4,5])
new = arr[arr%2==0].astype(bool)
print(new)

[ True  True]


In [60]:
#45

# Filter even numbers using boolean indexing.

# Input: [1,2,3,4,5,6]
# Output:
# [2 4 6]

import numpy as np

arr = np.array([1,2,3,4,5,6])
arr1 = arr[arr%2==0]
print(arr1)

[2 4 6]


# Some useful questions and topic

In [61]:
#46
# Find shape of array.
# Input:
# [[1,2,3],[4,5,6]]
# Output:
# (2,3)
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(np.shape(arr)) 



(2, 3)


In [62]:
#47
# Find dimensions of array.
# Input:
# [[1,2,3],[4,5,6]]
# Output:
# 2
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(np.ndim(arr)) 
#48
# Find total number of elements in array.
# Input:
# [[1,2,3],[4,5,6]]
# Output:
# 6
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(np.size(arr)) 

2
6


In [63]:
#49
# Reshape 1D array into 2x3 matrix.
# Input:
# [1,2,3,4,5,6]
# Output:
# [[1 2 3]
#  [4 5 6]]
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [64]:
#50
# Flatten a 2D array into 1D array.
# Input:
# [[1,2],[3,4]]
# Output:
# [1 2 3 4]
import numpy as np
arr = np.array([[1,2],[3,4]])
print(arr.reshape(-1))

[1 2 3 4]


In [65]:
#51
# Transpose a matrix.
# Input:
# [[1,2,3],
#  [4,5,6]]
# Output:
# [[1 4]
#  [2 5]
#  [3 6]]
import numpy as np
arr = np.array([[1,2,3],
               [4,5,6]])
print(np.transpose(arr))

[[1 4]
 [2 5]
 [3 6]]


In [66]:
#52
# Find mean of array.
# Input:
# [1,2,3,4]
# Output:
# 2.5
import numpy as np

arr = np.array([1,2,3,4])
m = np.mean(arr)
print(m)

2.5


In [67]:
#53
# Find median of array.
# Input:
# [1,2,3,4,5]
# Output:
# 3
import numpy as np

arr = np.array([1,2,3,4,5])
md = np.median(arr)
print(md)

3.0


In [68]:
#54
# Find cumulative sum.
# Input:
# [1,2,3,4]
# Output:
# [1 3 6 10]
import numpy as np

arr = np.array([1,2,3,4,5])
cs = np.cumulative_sum(arr)
print(cs)

[ 1  3  6 10 15]


In [69]:
#55
# Extract even numbers using boolean indexing.
# Input:
# [1,2,3,4,5,6]
# Output:
# [2 4 6]
import numpy as np

arr = np.array([1,2,3,4,5,6])
b = arr[arr%2==0]
print(b)

[2 4 6]


In [70]:
#56
# Replace all negative numbers with 0.
# Input:
# [1,-2,3,-4]
# Output:
# [1 0 3 0]

import numpy as np

arr = np.array([1,-2,3,-4])
new = np.where(arr<0,0,arr)
print(new)


[1 0 3 0]


In [71]:
#57
# Sort array in ascending order.
# Input:
# [5,2,8,1]
# Output:
# [1 2 5 8]
import numpy as np

arr = np.array([5,8,2,1])
new = np.sort(arr)
print(new)

[1 2 5 8]


In [72]:
#58
# Count non-zero elements.
# Input:
# [1,0,2,0,3]
# Output:
# 3
import numpy as np

arr = np.array([1,0,2,0,3])

count = np.count_nonzero(arr)
print(count)

3


In [73]:
#59
# Find sine values of array.
# Input:
# [0, π/2, π]
# Output:
# [0. 1. 0.]

import numpy as np

a = np.array([0, np.pi/2,np.pi])
b = np.sin(a)
print(b)


[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [74]:
#60
# Find cosine values of array.
# Input:
# [0, π]
# Output:
# [ 1. -1.]
import numpy as np

a = np.array([0,np.pi])
b = np.cos(a)
print(b)

[ 1. -1.]


In [75]:
#61
# Apply ceil function.
# Input:
# [1.2, 2.8, 3.1]
# Output:
# [2. 3. 4.]
import numpy as np

arr = np.array([1.2, 2.8, 3.1])
b = np.ceil(arr)
print(b)

[2. 3. 4.]


In [76]:
#62
# Apply floor function.
# Input:
# [1.2, 2.8, 3.9]
# Output:
# [1. 2. 3.]
import numpy as np

arr = np.array([1.2, 2.8, 3.1])
b = np.floor(arr)
print(b)

[1. 2. 3.]


In [77]:
#63
# Apply round function.
# Input:
# [1.4, 2.6, 3.5]
# Output:
# [1. 3. 4.]
import numpy as np

arr = np.array([1.4, 2.6, 3.5])
b = np.round(arr)
print(b)

[1. 3. 4.]


In [78]:
#64
# Get current date using NumPy datetime.


import numpy as np

current_date = np.datetime64("today")
print(current_date)

# Add 5 days to current date.
new_date = current_date + np.timedelta64(5, 'D')
print(new_date)

2026-05-17
2026-05-22


In [79]:
#65
# Find difference between two dates.
# Input:
# 2026-05-01 and 2026-05-16
# Output:
# 15 days

import numpy as np

a = np.datetime64("2026-05-01")
b = np.datetime64("2026-05-16")

print(b-a)

15 days


In [80]:
#66
# Convert string to NumPy datetime.
date = np.datetime64('2026-12-25')
print(date)



2026-12-25


In [81]:
#67
# Create date range using arange().
# Output:
# ['2026-05-01' '2026-05-02' ...]
dates = np.arange('2026-05-01', '2026-05-06', dtype='datetime64[D]')
print(dates)

['2026-05-01' '2026-05-02' '2026-05-03' '2026-05-04' '2026-05-05']


In [82]:
#68
# Find current year from datetime.
year = str(current_date)[:4]
print(year)

2026


In [83]:
#69
# Create datetime with specific date.
# Input:
# 2026-12-25
specific_date = np.datetime64('2026-12-25')
print(specific_date)

2026-12-25
